# Generated by Django 4.0 on 2023-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('flavour', models.CharField(max_length=200)),
                ('shape', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('weight', models.CharField(max_length=250)),
                ('layer', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2550)),
            ],
        ),
    ]
