# Generated by Django 4.0 on 2023-03-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cakebox_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakebox',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
